<?php
/**
 * StatoPendenza
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Pendenze
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Pendenze
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.16.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Pendenze\Model;
use \GovPay\Pendenze\ObjectSerializer;

/**
 * StatoPendenza Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Pendenze
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatoPendenza
{
    /**
     * Possible values of this enum
     */
    public const ESEGUITA = 'ESEGUITA';

    public const NON_ESEGUITA = 'NON_ESEGUITA';

    public const ESEGUITA_PARZIALE = 'ESEGUITA_PARZIALE';

    public const ANNULLATA = 'ANNULLATA';

    public const SCADUTA = 'SCADUTA';

    public const ANOMALA = 'ANOMALA';

    public const INCASSATA = 'INCASSATA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ESEGUITA,
            self::NON_ESEGUITA,
            self::ESEGUITA_PARZIALE,
            self::ANNULLATA,
            self::SCADUTA,
            self::ANOMALA,
            self::INCASSATA
        ];
    }
}


