<?php
/**
 * TipoPendenzaTipologia
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Pendenze
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Pendenze
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.16.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Pendenze\Model;
use \GovPay\Pendenze\ObjectSerializer;

/**
 * TipoPendenzaTipologia Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Pendenze
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TipoPendenzaTipologia
{
    /**
     * Possible values of this enum
     */
    public const SPONTANEO = 'spontaneo';

    public const DOVUTO = 'dovuto';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SPONTANEO,
            self::DOVUTO
        ];
    }
}


