<?php
/**
 * CartRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PagoPA\CheckoutEc
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Checkout - EC API
 *
 * Checkout API for EC
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PagoPA\CheckoutEc\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CartRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CartRequest
 * @package     PagoPA\CheckoutEc
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CartRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CartRequest"
     */
    public function testCartRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email_notice"
     */
    public function testPropertyEmailNotice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_notices"
     */
    public function testPropertyPaymentNotices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "return_urls"
     */
    public function testPropertyReturnUrls()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_cart"
     */
    public function testPropertyIdCart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "all_ccp"
     */
    public function testPropertyAllCcp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
