<?php
/**
 * EsitoOperazionePendenza
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Backoffice\Model;

use \ArrayAccess;
use \GovPay\Backoffice\ObjectSerializer;

/**
 * EsitoOperazionePendenza Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EsitoOperazionePendenza implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'esitoOperazionePendenza';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id_a2_a' => 'string',
        'id_pendenza' => 'string',
        'tipo_operazione' => '\GovPay\Backoffice\Model\TipoOperazionePendenza',
        'stato' => '\GovPay\Backoffice\Model\StatoOperazionePendenza',
        'esito' => 'string',
        'descrizione_esito' => 'string',
        'numero' => 'int',
        'dati' => '\GovPay\Backoffice\Model\EsitoOperazionePendenzaDati'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id_a2_a' => null,
        'id_pendenza' => null,
        'tipo_operazione' => null,
        'stato' => null,
        'esito' => null,
        'descrizione_esito' => null,
        'numero' => 'int64',
        'dati' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id_a2_a' => false,
        'id_pendenza' => false,
        'tipo_operazione' => false,
        'stato' => false,
        'esito' => false,
        'descrizione_esito' => false,
        'numero' => false,
        'dati' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_a2_a' => 'idA2A',
        'id_pendenza' => 'idPendenza',
        'tipo_operazione' => 'tipoOperazione',
        'stato' => 'stato',
        'esito' => 'esito',
        'descrizione_esito' => 'descrizioneEsito',
        'numero' => 'numero',
        'dati' => 'dati'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_a2_a' => 'setIdA2A',
        'id_pendenza' => 'setIdPendenza',
        'tipo_operazione' => 'setTipoOperazione',
        'stato' => 'setStato',
        'esito' => 'setEsito',
        'descrizione_esito' => 'setDescrizioneEsito',
        'numero' => 'setNumero',
        'dati' => 'setDati'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_a2_a' => 'getIdA2A',
        'id_pendenza' => 'getIdPendenza',
        'tipo_operazione' => 'getTipoOperazione',
        'stato' => 'getStato',
        'esito' => 'getEsito',
        'descrizione_esito' => 'getDescrizioneEsito',
        'numero' => 'getNumero',
        'dati' => 'getDati'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id_a2_a', $data ?? [], null);
        $this->setIfExists('id_pendenza', $data ?? [], null);
        $this->setIfExists('tipo_operazione', $data ?? [], null);
        $this->setIfExists('stato', $data ?? [], null);
        $this->setIfExists('esito', $data ?? [], null);
        $this->setIfExists('descrizione_esito', $data ?? [], null);
        $this->setIfExists('numero', $data ?? [], null);
        $this->setIfExists('dati', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id_a2_a'] === null) {
            $invalidProperties[] = "'id_a2_a' can't be null";
        }
        if ($this->container['id_pendenza'] === null) {
            $invalidProperties[] = "'id_pendenza' can't be null";
        }
        if ($this->container['tipo_operazione'] === null) {
            $invalidProperties[] = "'tipo_operazione' can't be null";
        }
        if ($this->container['stato'] === null) {
            $invalidProperties[] = "'stato' can't be null";
        }
        if ($this->container['esito'] === null) {
            $invalidProperties[] = "'esito' can't be null";
        }
        if ($this->container['descrizione_esito'] === null) {
            $invalidProperties[] = "'descrizione_esito' can't be null";
        }
        if ($this->container['numero'] === null) {
            $invalidProperties[] = "'numero' can't be null";
        }
        if ($this->container['dati'] === null) {
            $invalidProperties[] = "'dati' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_a2_a
     *
     * @return string
     */
    public function getIdA2A()
    {
        return $this->container['id_a2_a'];
    }

    /**
     * Sets id_a2_a
     *
     * @param string $id_a2_a Identificativo del gestionale responsabile della pendenza
     *
     * @return self
     */
    public function setIdA2A($id_a2_a)
    {
        if (is_null($id_a2_a)) {
            throw new \InvalidArgumentException('non-nullable id_a2_a cannot be null');
        }
        $this->container['id_a2_a'] = $id_a2_a;

        return $this;
    }

    /**
     * Gets id_pendenza
     *
     * @return string
     */
    public function getIdPendenza()
    {
        return $this->container['id_pendenza'];
    }

    /**
     * Sets id_pendenza
     *
     * @param string $id_pendenza Identificativo della pendenza nel gestionale responsabile
     *
     * @return self
     */
    public function setIdPendenza($id_pendenza)
    {
        if (is_null($id_pendenza)) {
            throw new \InvalidArgumentException('non-nullable id_pendenza cannot be null');
        }
        $this->container['id_pendenza'] = $id_pendenza;

        return $this;
    }

    /**
     * Gets tipo_operazione
     *
     * @return \GovPay\Backoffice\Model\TipoOperazionePendenza
     */
    public function getTipoOperazione()
    {
        return $this->container['tipo_operazione'];
    }

    /**
     * Sets tipo_operazione
     *
     * @param \GovPay\Backoffice\Model\TipoOperazionePendenza $tipo_operazione tipo_operazione
     *
     * @return self
     */
    public function setTipoOperazione($tipo_operazione)
    {
        if (is_null($tipo_operazione)) {
            throw new \InvalidArgumentException('non-nullable tipo_operazione cannot be null');
        }
        $this->container['tipo_operazione'] = $tipo_operazione;

        return $this;
    }

    /**
     * Gets stato
     *
     * @return \GovPay\Backoffice\Model\StatoOperazionePendenza
     */
    public function getStato()
    {
        return $this->container['stato'];
    }

    /**
     * Sets stato
     *
     * @param \GovPay\Backoffice\Model\StatoOperazionePendenza $stato stato
     *
     * @return self
     */
    public function setStato($stato)
    {
        if (is_null($stato)) {
            throw new \InvalidArgumentException('non-nullable stato cannot be null');
        }
        $this->container['stato'] = $stato;

        return $this;
    }

    /**
     * Gets esito
     *
     * @return string
     */
    public function getEsito()
    {
        return $this->container['esito'];
    }

    /**
     * Sets esito
     *
     * @param string $esito Esito Operazione
     *
     * @return self
     */
    public function setEsito($esito)
    {
        if (is_null($esito)) {
            throw new \InvalidArgumentException('non-nullable esito cannot be null');
        }
        $this->container['esito'] = $esito;

        return $this;
    }

    /**
     * Gets descrizione_esito
     *
     * @return string
     */
    public function getDescrizioneEsito()
    {
        return $this->container['descrizione_esito'];
    }

    /**
     * Sets descrizione_esito
     *
     * @param string $descrizione_esito Descrizione Esito Operazione
     *
     * @return self
     */
    public function setDescrizioneEsito($descrizione_esito)
    {
        if (is_null($descrizione_esito)) {
            throw new \InvalidArgumentException('non-nullable descrizione_esito cannot be null');
        }
        $this->container['descrizione_esito'] = $descrizione_esito;

        return $this;
    }

    /**
     * Gets numero
     *
     * @return int
     */
    public function getNumero()
    {
        return $this->container['numero'];
    }

    /**
     * Sets numero
     *
     * @param int $numero Progressivo Operazione
     *
     * @return self
     */
    public function setNumero($numero)
    {
        if (is_null($numero)) {
            throw new \InvalidArgumentException('non-nullable numero cannot be null');
        }
        $this->container['numero'] = $numero;

        return $this;
    }

    /**
     * Gets dati
     *
     * @return \GovPay\Backoffice\Model\EsitoOperazionePendenzaDati
     */
    public function getDati()
    {
        return $this->container['dati'];
    }

    /**
     * Sets dati
     *
     * @param \GovPay\Backoffice\Model\EsitoOperazionePendenzaDati $dati dati
     *
     * @return self
     */
    public function setDati($dati)
    {
        if (is_null($dati)) {
            throw new \InvalidArgumentException('non-nullable dati cannot be null');
        }
        $this->container['dati'] = $dati;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


