<?php
/**
 * EsitoRpt
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Backoffice\Model;
use \GovPay\Backoffice\ObjectSerializer;

/**
 * EsitoRpt Class Doc Comment
 *
 * @category Class
 * @description Esito della richiesta di pagamento:  * IN_CORSO: Pagamento in corso  * RIFIUTATO: Pagamento rifiutato  * ESEGUITO: Pagamento eseguito  * NON_ESEGUITO: Pagamento non eseguito  * ESEGUITO_PARZIALE: Pagamento parzialmente eseguito  * DECORRENZA: Decorrenza termini  * DECORRENZA_PARZIALE: Decorrenza termini parziale
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EsitoRpt
{
    /**
     * Possible values of this enum
     */
    public const IN_CORSO = 'IN_CORSO';

    public const RIFIUTATO = 'RIFIUTATO';

    public const ESEGUITO = 'ESEGUITO';

    public const NON_ESEGUITO = 'NON_ESEGUITO';

    public const ESEGUITO_PARZIALE = 'ESEGUITO_PARZIALE';

    public const DECORRENZA = 'DECORRENZA';

    public const DECORENNZA_PARZIALE = 'DECORENNZA_PARZIALE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::IN_CORSO,
            self::RIFIUTATO,
            self::ESEGUITO,
            self::NON_ESEGUITO,
            self::ESEGUITO_PARZIALE,
            self::DECORRENZA,
            self::DECORENNZA_PARZIALE
        ];
    }
}


