<?php
/**
 * StatoTracciatoPendenza
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Backoffice\Model;
use \GovPay\Backoffice\ObjectSerializer;

/**
 * StatoTracciatoPendenza Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatoTracciatoPendenza
{
    /**
     * Possible values of this enum
     */
    public const IN_ATTESA = 'IN_ATTESA';

    public const IN_ELABORAZIONE = 'IN_ELABORAZIONE';

    public const ESEGUITO = 'ESEGUITO';

    public const ESEGUITO_CON_ERRORI = 'ESEGUITO_CON_ERRORI';

    public const SCARTATO = 'SCARTATO';

    public const ELABORAZIONE_STAMPA = 'ELABORAZIONE_STAMPA';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::IN_ATTESA,
            self::IN_ELABORAZIONE,
            self::ESEGUITO,
            self::ESEGUITO_CON_ERRORI,
            self::SCARTATO,
            self::ELABORAZIONE_STAMPA
        ];
    }
}


