<?php
/**
 * TipoSogliaVincoloPagamento
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Backoffice\Model;
use \GovPay\Backoffice\ObjectSerializer;

/**
 * TipoSogliaVincoloPagamento Class Doc Comment
 *
 * @category Class
 * @description Indica se il pagamento deve avvenire entro o oltre la soglia di giorni indicata
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TipoSogliaVincoloPagamento
{
    /**
     * Possible values of this enum
     */
    public const ENTRO = 'ENTRO';

    public const OLTRE = 'OLTRE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ENTRO,
            self::OLTRE
        ];
    }
}


