<?php
/**
 * ApplicazioniApi
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Backoffice\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use GovPay\Backoffice\ApiException;
use GovPay\Backoffice\Configuration;
use GovPay\Backoffice\FormDataProcessor;
use GovPay\Backoffice\HeaderSelector;
use GovPay\Backoffice\ObjectSerializer;

/**
 * ApplicazioniApi Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApplicazioniApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'addApplicazione' => [
            'application/json',
        ],
        'findApplicazioni' => [
            'application/json',
        ],
        'getApplicazione' => [
            'application/json',
        ],
        'updateApplicazione' => [
            'application/json-patch+json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addApplicazione
     *
     * Aggiunge o aggiorna un&#39;applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\ApplicazionePost|null $applicazione_post applicazione_post (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addApplicazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function addApplicazione($id_a2_a, $applicazione_post = null, string $contentType = self::contentTypes['addApplicazione'][0])
    {
        $this->addApplicazioneWithHttpInfo($id_a2_a, $applicazione_post, $contentType);
    }

    /**
     * Operation addApplicazioneWithHttpInfo
     *
     * Aggiunge o aggiorna un&#39;applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\ApplicazionePost|null $applicazione_post (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addApplicazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function addApplicazioneWithHttpInfo($id_a2_a, $applicazione_post = null, string $contentType = self::contentTypes['addApplicazione'][0])
    {
        $request = $this->addApplicazioneRequest($id_a2_a, $applicazione_post, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FaultBean',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation addApplicazioneAsync
     *
     * Aggiunge o aggiorna un&#39;applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\ApplicazionePost|null $applicazione_post (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addApplicazioneAsync($id_a2_a, $applicazione_post = null, string $contentType = self::contentTypes['addApplicazione'][0])
    {
        return $this->addApplicazioneAsyncWithHttpInfo($id_a2_a, $applicazione_post, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addApplicazioneAsyncWithHttpInfo
     *
     * Aggiunge o aggiorna un&#39;applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\ApplicazionePost|null $applicazione_post (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addApplicazioneAsyncWithHttpInfo($id_a2_a, $applicazione_post = null, string $contentType = self::contentTypes['addApplicazione'][0])
    {
        $returnType = '';
        $request = $this->addApplicazioneRequest($id_a2_a, $applicazione_post, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addApplicazione'
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\ApplicazionePost|null $applicazione_post (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addApplicazioneRequest($id_a2_a, $applicazione_post = null, string $contentType = self::contentTypes['addApplicazione'][0])
    {

        // verify the required parameter 'id_a2_a' is set
        if ($id_a2_a === null || (is_array($id_a2_a) && count($id_a2_a) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_a2_a when calling addApplicazione'
            );
        }
        if (!preg_match("/(^[a-zA-Z0-9\\-_]{1,35}$)/", $id_a2_a)) {
            throw new \InvalidArgumentException("invalid value for \"id_a2_a\" when calling ApplicazioniApi.addApplicazione, must conform to the pattern /(^[a-zA-Z0-9\\-_]{1,35}$)/.");
        }
        


        $resourcePath = '/applicazioni/{idA2A}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id_a2_a !== null) {
            $resourcePath = str_replace(
                '{' . 'idA2A' . '}',
                ObjectSerializer::toPathValue($id_a2_a),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($applicazione_post)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($applicazione_post));
            } else {
                $httpBody = $applicazione_post;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findApplicazioni
     *
     * Elenco delle applicazioni censite su sistema
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string|null $ordinamento csv dei campi su cui ordinare i risultati, preceduti da + o - per ascendente o discendente (default ascendente)  * idA2A (optional, default to '+idA2A')
     * @param  string|null $campi csv dei campi da includere nella risposta (default tutti) (optional)
     * @param  bool|null $abilitato Restrizione ai soli elementi abilitati o disabilitati (optional)
     * @param  string|null $id_a2_a Identificativo del gestionale proprietario della pendenza (optional)
     * @param  string|null $principal Restrizione ai soli elementi con principal indicato (optional)
     * @param  bool|null $metadati_paginazione Indica se il servizio calcola e valorizza i dati di paginazione o meno (optional, default to true)
     * @param  bool|null $max_risultati Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findApplicazioni'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GovPay\Backoffice\Model\FindApplicazioni200Response|\GovPay\Backoffice\Model\FaultBean
     */
    public function findApplicazioni($pagina = 1, $risultati_per_pagina = 25, $ordinamento = '+idA2A', $campi = null, $abilitato = null, $id_a2_a = null, $principal = null, $metadati_paginazione = true, $max_risultati = true, string $contentType = self::contentTypes['findApplicazioni'][0])
    {
        list($response) = $this->findApplicazioniWithHttpInfo($pagina, $risultati_per_pagina, $ordinamento, $campi, $abilitato, $id_a2_a, $principal, $metadati_paginazione, $max_risultati, $contentType);
        return $response;
    }

    /**
     * Operation findApplicazioniWithHttpInfo
     *
     * Elenco delle applicazioni censite su sistema
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string|null $ordinamento csv dei campi su cui ordinare i risultati, preceduti da + o - per ascendente o discendente (default ascendente)  * idA2A (optional, default to '+idA2A')
     * @param  string|null $campi csv dei campi da includere nella risposta (default tutti) (optional)
     * @param  bool|null $abilitato Restrizione ai soli elementi abilitati o disabilitati (optional)
     * @param  string|null $id_a2_a Identificativo del gestionale proprietario della pendenza (optional)
     * @param  string|null $principal Restrizione ai soli elementi con principal indicato (optional)
     * @param  bool|null $metadati_paginazione Indica se il servizio calcola e valorizza i dati di paginazione o meno (optional, default to true)
     * @param  bool|null $max_risultati Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findApplicazioni'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GovPay\Backoffice\Model\FindApplicazioni200Response|\GovPay\Backoffice\Model\FaultBean, HTTP status code, HTTP response headers (array of strings)
     */
    public function findApplicazioniWithHttpInfo($pagina = 1, $risultati_per_pagina = 25, $ordinamento = '+idA2A', $campi = null, $abilitato = null, $id_a2_a = null, $principal = null, $metadati_paginazione = true, $max_risultati = true, string $contentType = self::contentTypes['findApplicazioni'][0])
    {
        $request = $this->findApplicazioniRequest($pagina, $risultati_per_pagina, $ordinamento, $campi, $abilitato, $id_a2_a, $principal, $metadati_paginazione, $max_risultati, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FindApplicazioni200Response',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FaultBean',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GovPay\Backoffice\Model\FindApplicazioni200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FindApplicazioni200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FaultBean',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation findApplicazioniAsync
     *
     * Elenco delle applicazioni censite su sistema
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string|null $ordinamento csv dei campi su cui ordinare i risultati, preceduti da + o - per ascendente o discendente (default ascendente)  * idA2A (optional, default to '+idA2A')
     * @param  string|null $campi csv dei campi da includere nella risposta (default tutti) (optional)
     * @param  bool|null $abilitato Restrizione ai soli elementi abilitati o disabilitati (optional)
     * @param  string|null $id_a2_a Identificativo del gestionale proprietario della pendenza (optional)
     * @param  string|null $principal Restrizione ai soli elementi con principal indicato (optional)
     * @param  bool|null $metadati_paginazione Indica se il servizio calcola e valorizza i dati di paginazione o meno (optional, default to true)
     * @param  bool|null $max_risultati Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findApplicazioni'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findApplicazioniAsync($pagina = 1, $risultati_per_pagina = 25, $ordinamento = '+idA2A', $campi = null, $abilitato = null, $id_a2_a = null, $principal = null, $metadati_paginazione = true, $max_risultati = true, string $contentType = self::contentTypes['findApplicazioni'][0])
    {
        return $this->findApplicazioniAsyncWithHttpInfo($pagina, $risultati_per_pagina, $ordinamento, $campi, $abilitato, $id_a2_a, $principal, $metadati_paginazione, $max_risultati, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findApplicazioniAsyncWithHttpInfo
     *
     * Elenco delle applicazioni censite su sistema
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string|null $ordinamento csv dei campi su cui ordinare i risultati, preceduti da + o - per ascendente o discendente (default ascendente)  * idA2A (optional, default to '+idA2A')
     * @param  string|null $campi csv dei campi da includere nella risposta (default tutti) (optional)
     * @param  bool|null $abilitato Restrizione ai soli elementi abilitati o disabilitati (optional)
     * @param  string|null $id_a2_a Identificativo del gestionale proprietario della pendenza (optional)
     * @param  string|null $principal Restrizione ai soli elementi con principal indicato (optional)
     * @param  bool|null $metadati_paginazione Indica se il servizio calcola e valorizza i dati di paginazione o meno (optional, default to true)
     * @param  bool|null $max_risultati Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findApplicazioni'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findApplicazioniAsyncWithHttpInfo($pagina = 1, $risultati_per_pagina = 25, $ordinamento = '+idA2A', $campi = null, $abilitato = null, $id_a2_a = null, $principal = null, $metadati_paginazione = true, $max_risultati = true, string $contentType = self::contentTypes['findApplicazioni'][0])
    {
        $returnType = '\GovPay\Backoffice\Model\FindApplicazioni200Response';
        $request = $this->findApplicazioniRequest($pagina, $risultati_per_pagina, $ordinamento, $campi, $abilitato, $id_a2_a, $principal, $metadati_paginazione, $max_risultati, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findApplicazioni'
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string|null $ordinamento csv dei campi su cui ordinare i risultati, preceduti da + o - per ascendente o discendente (default ascendente)  * idA2A (optional, default to '+idA2A')
     * @param  string|null $campi csv dei campi da includere nella risposta (default tutti) (optional)
     * @param  bool|null $abilitato Restrizione ai soli elementi abilitati o disabilitati (optional)
     * @param  string|null $id_a2_a Identificativo del gestionale proprietario della pendenza (optional)
     * @param  string|null $principal Restrizione ai soli elementi con principal indicato (optional)
     * @param  bool|null $metadati_paginazione Indica se il servizio calcola e valorizza i dati di paginazione o meno (optional, default to true)
     * @param  bool|null $max_risultati Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati (optional, default to true)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findApplicazioni'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findApplicazioniRequest($pagina = 1, $risultati_per_pagina = 25, $ordinamento = '+idA2A', $campi = null, $abilitato = null, $id_a2_a = null, $principal = null, $metadati_paginazione = true, $max_risultati = true, string $contentType = self::contentTypes['findApplicazioni'][0])
    {

        if ($pagina !== null && $pagina < 1) {
            throw new \InvalidArgumentException('invalid value for "$pagina" when calling ApplicazioniApi.findApplicazioni, must be bigger than or equal to 1.');
        }
        
        if ($risultati_per_pagina !== null && $risultati_per_pagina > 200) {
            throw new \InvalidArgumentException('invalid value for "$risultati_per_pagina" when calling ApplicazioniApi.findApplicazioni, must be smaller than or equal to 200.');
        }
        if ($risultati_per_pagina !== null && $risultati_per_pagina < 0) {
            throw new \InvalidArgumentException('invalid value for "$risultati_per_pagina" when calling ApplicazioniApi.findApplicazioni, must be bigger than or equal to 0.');
        }
        








        $resourcePath = '/applicazioni';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pagina,
            'pagina', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $risultati_per_pagina,
            'risultatiPerPagina', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ordinamento,
            'ordinamento', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $campi,
            'campi', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $abilitato,
            'abilitato', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $id_a2_a,
            'idA2A', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $principal,
            'principal', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $metadati_paginazione,
            'metadatiPaginazione', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $max_risultati,
            'maxRisultati', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getApplicazione
     *
     * Lettura dei dati di una applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApplicazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GovPay\Backoffice\Model\Applicazione|\GovPay\Backoffice\Model\FaultBean
     */
    public function getApplicazione($id_a2_a, string $contentType = self::contentTypes['getApplicazione'][0])
    {
        list($response) = $this->getApplicazioneWithHttpInfo($id_a2_a, $contentType);
        return $response;
    }

    /**
     * Operation getApplicazioneWithHttpInfo
     *
     * Lettura dei dati di una applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApplicazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GovPay\Backoffice\Model\Applicazione|\GovPay\Backoffice\Model\FaultBean, HTTP status code, HTTP response headers (array of strings)
     */
    public function getApplicazioneWithHttpInfo($id_a2_a, string $contentType = self::contentTypes['getApplicazione'][0])
    {
        $request = $this->getApplicazioneRequest($id_a2_a, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\Applicazione',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FaultBean',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GovPay\Backoffice\Model\Applicazione',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\Applicazione',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FaultBean',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getApplicazioneAsync
     *
     * Lettura dei dati di una applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getApplicazioneAsync($id_a2_a, string $contentType = self::contentTypes['getApplicazione'][0])
    {
        return $this->getApplicazioneAsyncWithHttpInfo($id_a2_a, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getApplicazioneAsyncWithHttpInfo
     *
     * Lettura dei dati di una applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getApplicazioneAsyncWithHttpInfo($id_a2_a, string $contentType = self::contentTypes['getApplicazione'][0])
    {
        $returnType = '\GovPay\Backoffice\Model\Applicazione';
        $request = $this->getApplicazioneRequest($id_a2_a, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getApplicazione'
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getApplicazioneRequest($id_a2_a, string $contentType = self::contentTypes['getApplicazione'][0])
    {

        // verify the required parameter 'id_a2_a' is set
        if ($id_a2_a === null || (is_array($id_a2_a) && count($id_a2_a) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_a2_a when calling getApplicazione'
            );
        }
        if (!preg_match("/(^[a-zA-Z0-9\\-_]{1,35}$)/", $id_a2_a)) {
            throw new \InvalidArgumentException("invalid value for \"id_a2_a\" when calling ApplicazioniApi.getApplicazione, must conform to the pattern /(^[a-zA-Z0-9\\-_]{1,35}$)/.");
        }
        

        $resourcePath = '/applicazioni/{idA2A}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id_a2_a !== null) {
            $resourcePath = str_replace(
                '{' . 'idA2A' . '}',
                ObjectSerializer::toPathValue($id_a2_a),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateApplicazione
     *
     * Aggiorna selettivamente campi di un Applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\PatchOp[] $patch_op patch_op (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateApplicazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GovPay\Backoffice\Model\Applicazione|\GovPay\Backoffice\Model\FaultBean|\GovPay\Backoffice\Model\FaultBean
     */
    public function updateApplicazione($id_a2_a, $patch_op, string $contentType = self::contentTypes['updateApplicazione'][0])
    {
        list($response) = $this->updateApplicazioneWithHttpInfo($id_a2_a, $patch_op, $contentType);
        return $response;
    }

    /**
     * Operation updateApplicazioneWithHttpInfo
     *
     * Aggiorna selettivamente campi di un Applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\PatchOp[] $patch_op (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateApplicazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GovPay\Backoffice\Model\Applicazione|\GovPay\Backoffice\Model\FaultBean|\GovPay\Backoffice\Model\FaultBean, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateApplicazioneWithHttpInfo($id_a2_a, $patch_op, string $contentType = self::contentTypes['updateApplicazione'][0])
    {
        $request = $this->updateApplicazioneRequest($id_a2_a, $patch_op, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\Applicazione',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FaultBean',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FaultBean',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GovPay\Backoffice\Model\Applicazione',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\Applicazione',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FaultBean',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FaultBean',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateApplicazioneAsync
     *
     * Aggiorna selettivamente campi di un Applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\PatchOp[] $patch_op (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateApplicazioneAsync($id_a2_a, $patch_op, string $contentType = self::contentTypes['updateApplicazione'][0])
    {
        return $this->updateApplicazioneAsyncWithHttpInfo($id_a2_a, $patch_op, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateApplicazioneAsyncWithHttpInfo
     *
     * Aggiorna selettivamente campi di un Applicazione
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\PatchOp[] $patch_op (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateApplicazioneAsyncWithHttpInfo($id_a2_a, $patch_op, string $contentType = self::contentTypes['updateApplicazione'][0])
    {
        $returnType = '\GovPay\Backoffice\Model\Applicazione';
        $request = $this->updateApplicazioneRequest($id_a2_a, $patch_op, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateApplicazione'
     *
     * @param  string $id_a2_a Identificativo dell&#39;applicazione (required)
     * @param  \GovPay\Backoffice\Model\PatchOp[] $patch_op (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateApplicazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateApplicazioneRequest($id_a2_a, $patch_op, string $contentType = self::contentTypes['updateApplicazione'][0])
    {

        // verify the required parameter 'id_a2_a' is set
        if ($id_a2_a === null || (is_array($id_a2_a) && count($id_a2_a) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_a2_a when calling updateApplicazione'
            );
        }
        if (!preg_match("/(^[a-zA-Z0-9\\-_]{1,35}$)/", $id_a2_a)) {
            throw new \InvalidArgumentException("invalid value for \"id_a2_a\" when calling ApplicazioniApi.updateApplicazione, must conform to the pattern /(^[a-zA-Z0-9\\-_]{1,35}$)/.");
        }
        
        // verify the required parameter 'patch_op' is set
        if ($patch_op === null || (is_array($patch_op) && count($patch_op) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $patch_op when calling updateApplicazione'
            );
        }


        $resourcePath = '/applicazioni/{idA2A}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id_a2_a !== null) {
            $resourcePath = str_replace(
                '{' . 'idA2A' . '}',
                ObjectSerializer::toPathValue($id_a2_a),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($patch_op)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($patch_op));
            } else {
                $httpBody = $patch_op;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
