<?php
/**
 * OperazioniApi
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Backoffice\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use GovPay\Backoffice\ApiException;
use GovPay\Backoffice\Configuration;
use GovPay\Backoffice\FormDataProcessor;
use GovPay\Backoffice\HeaderSelector;
use GovPay\Backoffice\ObjectSerializer;

/**
 * OperazioniApi Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OperazioniApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'findOperazioni' => [
            'application/json',
        ],
        'getOperazione' => [
            'application/json',
        ],
        'getStatoOperazione' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation findOperazioni
     *
     * Lista delle operazioni disponibili
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOperazioni'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GovPay\Backoffice\Model\FindOperazioni201Response
     */
    public function findOperazioni($pagina = 1, $risultati_per_pagina = 25, string $contentType = self::contentTypes['findOperazioni'][0])
    {
        list($response) = $this->findOperazioniWithHttpInfo($pagina, $risultati_per_pagina, $contentType);
        return $response;
    }

    /**
     * Operation findOperazioniWithHttpInfo
     *
     * Lista delle operazioni disponibili
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOperazioni'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GovPay\Backoffice\Model\FindOperazioni201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function findOperazioniWithHttpInfo($pagina = 1, $risultati_per_pagina = 25, string $contentType = self::contentTypes['findOperazioni'][0])
    {
        $request = $this->findOperazioniRequest($pagina, $risultati_per_pagina, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FindOperazioni201Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GovPay\Backoffice\Model\FindOperazioni201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FindOperazioni201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation findOperazioniAsync
     *
     * Lista delle operazioni disponibili
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOperazioni'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findOperazioniAsync($pagina = 1, $risultati_per_pagina = 25, string $contentType = self::contentTypes['findOperazioni'][0])
    {
        return $this->findOperazioniAsyncWithHttpInfo($pagina, $risultati_per_pagina, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findOperazioniAsyncWithHttpInfo
     *
     * Lista delle operazioni disponibili
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOperazioni'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findOperazioniAsyncWithHttpInfo($pagina = 1, $risultati_per_pagina = 25, string $contentType = self::contentTypes['findOperazioni'][0])
    {
        $returnType = '\GovPay\Backoffice\Model\FindOperazioni201Response';
        $request = $this->findOperazioniRequest($pagina, $risultati_per_pagina, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findOperazioni'
     *
     * @param  int|null $pagina Numero di pagina dei risultati (optional, default to 1)
     * @param  int|null $risultati_per_pagina Numero di risultati richiesti (max 5000) (optional, default to 25)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findOperazioni'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findOperazioniRequest($pagina = 1, $risultati_per_pagina = 25, string $contentType = self::contentTypes['findOperazioni'][0])
    {

        if ($pagina !== null && $pagina < 1) {
            throw new \InvalidArgumentException('invalid value for "$pagina" when calling OperazioniApi.findOperazioni, must be bigger than or equal to 1.');
        }
        
        if ($risultati_per_pagina !== null && $risultati_per_pagina > 200) {
            throw new \InvalidArgumentException('invalid value for "$risultati_per_pagina" when calling OperazioniApi.findOperazioni, must be smaller than or equal to 200.');
        }
        if ($risultati_per_pagina !== null && $risultati_per_pagina < 0) {
            throw new \InvalidArgumentException('invalid value for "$risultati_per_pagina" when calling OperazioniApi.findOperazioni, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/operazioni';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pagina,
            'pagina', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $risultati_per_pagina,
            'risultatiPerPagina', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getOperazione
     *
     * Esecuzione di una operazione interne
     *
     * @param  string $id_operazione Identificativo dell&#39;operazione da eseguire (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOperazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GovPay\Backoffice\Model\Operazione|\GovPay\Backoffice\Model\FaultBean
     */
    public function getOperazione($id_operazione, string $contentType = self::contentTypes['getOperazione'][0])
    {
        list($response) = $this->getOperazioneWithHttpInfo($id_operazione, $contentType);
        return $response;
    }

    /**
     * Operation getOperazioneWithHttpInfo
     *
     * Esecuzione di una operazione interne
     *
     * @param  string $id_operazione Identificativo dell&#39;operazione da eseguire (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOperazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GovPay\Backoffice\Model\Operazione|\GovPay\Backoffice\Model\FaultBean, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOperazioneWithHttpInfo($id_operazione, string $contentType = self::contentTypes['getOperazione'][0])
    {
        $request = $this->getOperazioneRequest($id_operazione, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\Operazione',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FaultBean',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GovPay\Backoffice\Model\Operazione',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\Operazione',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FaultBean',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getOperazioneAsync
     *
     * Esecuzione di una operazione interne
     *
     * @param  string $id_operazione Identificativo dell&#39;operazione da eseguire (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOperazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOperazioneAsync($id_operazione, string $contentType = self::contentTypes['getOperazione'][0])
    {
        return $this->getOperazioneAsyncWithHttpInfo($id_operazione, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOperazioneAsyncWithHttpInfo
     *
     * Esecuzione di una operazione interne
     *
     * @param  string $id_operazione Identificativo dell&#39;operazione da eseguire (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOperazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOperazioneAsyncWithHttpInfo($id_operazione, string $contentType = self::contentTypes['getOperazione'][0])
    {
        $returnType = '\GovPay\Backoffice\Model\Operazione';
        $request = $this->getOperazioneRequest($id_operazione, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOperazione'
     *
     * @param  string $id_operazione Identificativo dell&#39;operazione da eseguire (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getOperazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getOperazioneRequest($id_operazione, string $contentType = self::contentTypes['getOperazione'][0])
    {

        // verify the required parameter 'id_operazione' is set
        if ($id_operazione === null || (is_array($id_operazione) && count($id_operazione) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_operazione when calling getOperazione'
            );
        }


        $resourcePath = '/operazioni/{idOperazione}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id_operazione !== null) {
            $resourcePath = str_replace(
                '{' . 'idOperazione' . '}',
                ObjectSerializer::toPathValue($id_operazione),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStatoOperazione
     *
     * Stato di elaborazione di una operazione
     *
     * @param  string $id Identificativo dell&#39;istanza di operazione eseguita (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStatoOperazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \GovPay\Backoffice\Model\EsitoOperazione|\GovPay\Backoffice\Model\FaultBean
     */
    public function getStatoOperazione($id, string $contentType = self::contentTypes['getStatoOperazione'][0])
    {
        list($response) = $this->getStatoOperazioneWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getStatoOperazioneWithHttpInfo
     *
     * Stato di elaborazione di una operazione
     *
     * @param  string $id Identificativo dell&#39;istanza di operazione eseguita (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStatoOperazione'] to see the possible values for this operation
     *
     * @throws \GovPay\Backoffice\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \GovPay\Backoffice\Model\EsitoOperazione|\GovPay\Backoffice\Model\FaultBean, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStatoOperazioneWithHttpInfo($id, string $contentType = self::contentTypes['getStatoOperazione'][0])
    {
        $request = $this->getStatoOperazioneRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\EsitoOperazione',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\GovPay\Backoffice\Model\FaultBean',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\GovPay\Backoffice\Model\EsitoOperazione',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\EsitoOperazione',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\GovPay\Backoffice\Model\FaultBean',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getStatoOperazioneAsync
     *
     * Stato di elaborazione di una operazione
     *
     * @param  string $id Identificativo dell&#39;istanza di operazione eseguita (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStatoOperazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStatoOperazioneAsync($id, string $contentType = self::contentTypes['getStatoOperazione'][0])
    {
        return $this->getStatoOperazioneAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStatoOperazioneAsyncWithHttpInfo
     *
     * Stato di elaborazione di una operazione
     *
     * @param  string $id Identificativo dell&#39;istanza di operazione eseguita (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStatoOperazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStatoOperazioneAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getStatoOperazione'][0])
    {
        $returnType = '\GovPay\Backoffice\Model\EsitoOperazione';
        $request = $this->getStatoOperazioneRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStatoOperazione'
     *
     * @param  string $id Identificativo dell&#39;istanza di operazione eseguita (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStatoOperazione'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStatoOperazioneRequest($id, string $contentType = self::contentTypes['getStatoOperazione'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getStatoOperazione'
            );
        }


        $resourcePath = '/operazioni/stato/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
