<?php
/**
 * PendenzaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GovPay\Backoffice\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PendenzaTest Class Doc Comment
 *
 * @category    Class
 * @description Pendenza
 * @package     GovPay\Backoffice
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PendenzaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Pendenza"
     */
    public function testPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nome"
     */
    public function testPropertyNome()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "causale"
     */
    public function testPropertyCausale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "soggetto_pagatore"
     */
    public function testPropertySoggettoPagatore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "importo"
     */
    public function testPropertyImporto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_avviso"
     */
    public function testPropertyNumeroAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_caricamento"
     */
    public function testPropertyDataCaricamento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_validita"
     */
    public function testPropertyDataValidita()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_scadenza"
     */
    public function testPropertyDataScadenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "anno_riferimento"
     */
    public function testPropertyAnnoRiferimento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cartella_pagamento"
     */
    public function testPropertyCartellaPagamento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dati_allegati"
     */
    public function testPropertyDatiAllegati()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tassonomia"
     */
    public function testPropertyTassonomia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tassonomia_avviso"
     */
    public function testPropertyTassonomiaAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "direzione"
     */
    public function testPropertyDirezione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "divisione"
     */
    public function testPropertyDivisione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "documento"
     */
    public function testPropertyDocumento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_notifica_avviso"
     */
    public function testPropertyDataNotificaAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_promemoria_scadenza"
     */
    public function testPropertyDataPromemoriaScadenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "proprieta"
     */
    public function testPropertyProprieta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_a2_a"
     */
    public function testPropertyIdA2A()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_pendenza"
     */
    public function testPropertyIdPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pendenza"
     */
    public function testPropertyTipoPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dominio"
     */
    public function testPropertyDominio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unita_operativa"
     */
    public function testPropertyUnitaOperativa()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stato"
     */
    public function testPropertyStato()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descrizione_stato"
     */
    public function testPropertyDescrizioneStato()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iuv_avviso"
     */
    public function testPropertyIuvAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_ultimo_aggiornamento"
     */
    public function testPropertyDataUltimoAggiornamento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_pagamento"
     */
    public function testPropertyDataPagamento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "importo_pagato"
     */
    public function testPropertyImportoPagato()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "importo_incassato"
     */
    public function testPropertyImportoIncassato()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iuv_pagamento"
     */
    public function testPropertyIuvPagamento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "anomalo"
     */
    public function testPropertyAnomalo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "verificato"
     */
    public function testPropertyVerificato()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo"
     */
    public function testPropertyTipo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_ultima_modifica_aca"
     */
    public function testPropertyDataUltimaModificaAca()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_ultima_comunicazione_aca"
     */
    public function testPropertyDataUltimaComunicazioneAca()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "voci"
     */
    public function testPropertyVoci()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rpp"
     */
    public function testPropertyRpp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pagamenti"
     */
    public function testPropertyPagamenti()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "allegati"
     */
    public function testPropertyAllegati()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
