<?php
/**
 * ProprietaPendenzaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GovPay\Backoffice\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProprietaPendenzaTest Class Doc Comment
 *
 * @category    Class
 * @description Dati supporto per la gestione del ciclo di vita della pendenza.
 * @package     GovPay\Backoffice
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ProprietaPendenzaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProprietaPendenza"
     */
    public function testProprietaPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lingua_secondaria"
     */
    public function testPropertyLinguaSecondaria()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "descrizione_importo"
     */
    public function testPropertyDescrizioneImporto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "linea_testo_ricevuta1"
     */
    public function testPropertyLineaTestoRicevuta1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "linea_testo_ricevuta2"
     */
    public function testPropertyLineaTestoRicevuta2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lingua_secondaria_causale"
     */
    public function testPropertyLinguaSecondariaCausale()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "informativa_importo_avviso"
     */
    public function testPropertyInformativaImportoAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lingua_secondaria_informativa_importo_avviso"
     */
    public function testPropertyLinguaSecondariaInformativaImportoAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "data_scandenza_avviso"
     */
    public function testPropertyDataScandenzaAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
