<?php
/**
 * StatisticaQuadraturaTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GovPay\Backoffice\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * StatisticaQuadraturaTest Class Doc Comment
 *
 * @category    Class
 * @description StatisticaQuadratura
 * @package     GovPay\Backoffice
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StatisticaQuadraturaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "StatisticaQuadratura"
     */
    public function testStatisticaQuadratura()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numero_pagamenti"
     */
    public function testPropertyNumeroPagamenti()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "importo"
     */
    public function testPropertyImporto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dettaglio"
     */
    public function testPropertyDettaglio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "direzione"
     */
    public function testPropertyDirezione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "divisione"
     */
    public function testPropertyDivisione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tassonomia"
     */
    public function testPropertyTassonomia()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tipo_pendenza"
     */
    public function testPropertyTipoPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dominio"
     */
    public function testPropertyDominio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unita_operativa"
     */
    public function testPropertyUnitaOperativa()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicazione"
     */
    public function testPropertyApplicazione()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
