<?php
/**
 * StatoRiconciliazione
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Ragioneria
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Ragioneria
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GovPay\Ragioneria\Model;
use \GovPay\Ragioneria\ObjectSerializer;

/**
 * StatoRiconciliazione Class Doc Comment
 *
 * @category Class
 * @description Stato della riconciliazione  * IN_ELABORAZIONE: In elaborazione  * ACQUISITA: Acquisizione completata con successo  * ERRORE: Acquisizione completata con errore
 * @package  GovPay\Ragioneria
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StatoRiconciliazione
{
    /**
     * Possible values of this enum
     */
    public const IN_ELABORAZIONE = 'IN_ELABORAZIONE';

    public const ACQUISITA = 'ACQUISITA';

    public const ERRORE = 'ERRORE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::IN_ELABORAZIONE,
            self::ACQUISITA,
            self::ERRORE
        ];
    }
}


