<?php
/**
 * RicevuteApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Ragioneria
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Ragioneria
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GovPay\Ragioneria\Test\Api;

use \GovPay\Ragioneria\Configuration;
use \GovPay\Ragioneria\ApiException;
use \GovPay\Ragioneria\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RicevuteApiTest Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Ragioneria
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RicevuteApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for findRicevute
     *
     * Ricerca delle ricevute di pagamento.
     *
     */
    public function testFindRicevute()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRicevuta
     *
     * Acquisizione di una ricevuta di avvenuto pagamento pagoPA.
     *
     */
    public function testGetRicevuta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
