<?php
/**
 * PendenzeApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * GovPay - API Backoffice
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.45.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GovPay\Backoffice\Test\Api;

use \GovPay\Backoffice\Configuration;
use \GovPay\Backoffice\ApiException;
use \GovPay\Backoffice\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PendenzeApiTest Class Doc Comment
 *
 * @category Class
 * @package  GovPay\Backoffice
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PendenzeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addPendenza
     *
     * Aggiunge una nuova Pendenza.
     *
     */
    public function testAddPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addPendenzaCustom
     *
     * Aggiunge una nuova Pendenza in formato custom.
     *
     */
    public function testAddPendenzaCustom()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addPendenzaPOST
     *
     * Aggiunge una nuova Pendenza.
     *
     */
    public function testAddPendenzaPOST()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addTracciatoPendenze
     *
     * Aggiunge un nuovo Tracciato di Pendenze.
     *
     */
    public function testAddTracciatoPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addTracciatoPendenzeDominio
     *
     * Aggiunge un nuovo Tracciato di Pendenze in formato csv.
     *
     */
    public function testAddTracciatoPendenzeDominio()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addTracciatoPendenzeDominioTipoPendenza
     *
     * Aggiunge un nuovo Tracciato di Pendenze in formato csv.
     *
     */
    public function testAddTracciatoPendenzeDominioTipoPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findOperazioniTracciatoPendenze
     *
     * Elenco delle Operazioni relative ad un Tracciato.
     *
     */
    public function testFindOperazioniTracciatoPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findPendenze
     *
     * Elenco delle pendenze.
     *
     */
    public function testFindPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for findTracciatiPendenze
     *
     * Elenco dei Tracciati caricati.
     *
     */
    public function testFindTracciatiPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllegatoPendenza
     *
     * Allegato di una pendenza.
     *
     */
    public function testGetAllegatoPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAvvisiDocumento
     *
     * Documento di pagamento.
     *
     */
    public function testGetAvvisiDocumento()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAvviso
     *
     * Avviso di pagamento.
     *
     */
    public function testGetAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEsitoTracciatoPendenze
     *
     * Dettaglio esito di un Tracciato.
     *
     */
    public function testGetEsitoTracciatoPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPendenza
     *
     * Dettaglio di una Pendenza per identificativo.
     *
     */
    public function testGetPendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPendenzaByAvviso
     *
     * Dettaglio di una pendenza per riferimento Avviso.
     *
     */
    public function testGetPendenzaByAvviso()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRichiestaTracciatoPendenze
     *
     * Tracciato di richiesta.
     *
     */
    public function testGetRichiestaTracciatoPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getStampeTracciatoPendenze
     *
     * Avvisi di pagamento relativi al Tracciato.
     *
     */
    public function testGetStampeTracciatoPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTracciatoPendenze
     *
     * Dettaglio di un Tracciato.
     *
     */
    public function testGetTracciatoPendenze()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePendenza
     *
     * Annullamento o ripristino di una Pendenza.
     *
     */
    public function testUpdatePendenza()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
