<?php
/**
 * PaymentOptionModelResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PagoPA\GPD
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PagoPA API Debt Position
 *
 * Progetto Gestione Posizioni Debitorie
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PagoPA\GPD\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PaymentOptionModelResponseTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentOptionModelResponse
 * @package     PagoPA\GPD
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentOptionModelResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentOptionModelResponse"
     */
    public function testPaymentOptionModelResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nav"
     */
    public function testPropertyNav()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iuv"
     */
    public function testPropertyIuv()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "organization_fiscal_code"
     */
    public function testPropertyOrganizationFiscalCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_partial_payment"
     */
    public function testPropertyIsPartialPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "retention_date"
     */
    public function testPropertyRetentionDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_date"
     */
    public function testPropertyPaymentDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reporting_date"
     */
    public function testPropertyReportingDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inserted_date"
     */
    public function testPropertyInsertedDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notification_fee"
     */
    public function testPropertyNotificationFee()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "psp_company"
     */
    public function testPropertyPspCompany()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_receipt"
     */
    public function testPropertyIdReceipt()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_flow_reporting"
     */
    public function testPropertyIdFlowReporting()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last_updated_date"
     */
    public function testPropertyLastUpdatedDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_option_metadata"
     */
    public function testPropertyPaymentOptionMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transfer"
     */
    public function testPropertyTransfer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
