<?php
/**
 * TransferModelTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PagoPA\GPD
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PagoPA API Debt Position
 *
 * Progetto Gestione Posizioni Debitorie
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PagoPA\GPD\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TransferModelTest Class Doc Comment
 *
 * @category    Class
 * @description TransferModel
 * @package     PagoPA\GPD
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransferModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransferModel"
     */
    public function testTransferModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id_transfer"
     */
    public function testPropertyIdTransfer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "organization_fiscal_code"
     */
    public function testPropertyOrganizationFiscalCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "remittance_information"
     */
    public function testPropertyRemittanceInformation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "postal_iban"
     */
    public function testPropertyPostalIban()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stamp"
     */
    public function testPropertyStamp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transfer_metadata"
     */
    public function testPropertyTransferMetadata()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
