<?php
/**
 * TransferMetadataModelResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PagoPA\GPD
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PagoPA API Debt Position
 *
 * Progetto Gestione Posizioni Debitorie
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PagoPA\GPD\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TransferMetadataModelResponseTest Class Doc Comment
 *
 * @category    Class
 * @description TransferMetadataModelResponse
 * @package     PagoPA\GPD
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransferMetadataModelResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransferMetadataModelResponse"
     */
    public function testTransferMetadataModelResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
