<?php
/**
 * UpdateTransferIbanMassiveModelTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  PagoPA\GPD
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PagoPA API Debt Position
 *
 * Progetto Gestione Posizioni Debitorie
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace PagoPA\GPD\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateTransferIbanMassiveModelTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateTransferIbanMassiveModel
 * @package     PagoPA\GPD
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateTransferIbanMassiveModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateTransferIbanMassiveModel"
     */
    public function testUpdateTransferIbanMassiveModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "new_iban"
     */
    public function testPropertyNewIban()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
